### ISSUE TITLE
npm run dev 出错

### ISSUE THREAD

**Issue by a212150057** [vueadmin/parcel-vue#1]
G:\Tongue-master\parcel-vue-master\parcel-vue-master>cnpm run dev

> parcel-tool@1.0.0 dev G:\Tongue-master\parcel-vue-master\parcel-vue-master
> parcel index.html

⏳  Building...
Server running at http://localhost:1234
🚨  G:\Tongue-master\parcel-vue-master\parcel-vue-master\src\app.vue:17:25: Cannot resolve dependency 'vue'
  15 | </style>
  16 |

**Comment by vueadmin** [comment]
拉取以后把 package-lock.json 删除 然后 npm i 最后再npm run dev
